gText_NewGame_HelpDocs1:: @ 81C582D
    .string "The various buttons will be explained in the\n"
    .string "order of their importance.$"

gText_NewGame_HelpDocs2:: @ 81C5875
    .string "Moves the main character.\n"
    .string "Also used to choose various\n"
    .string "headings and selections.$"

gText_NewGame_HelpDocs3:: @ 81C58BA
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gText_NewGame_HelpDocs4:: @ 81C58F9
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gText_NewGame_HelpDocs5:: @ 81C592B
    .string "Press this button to open the\n"
    .string "menu.$"

gText_NewGame_HelpDocs6:: @ 81C594F
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gText_NewGame_HelpDocs7:: @ 81C5981
    .string "Used to navigate certain menus.\n"
    .string "You may also configure this button\n"
    .string "as an alternate A button.$"

gText_NewGameAdventureIntro1::
    .string "You are about to enter a world where\n"
    .string "you will embark on a grand adventure\n"
    .string "of your very own.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and hints\n"
    .string "from every possible source.$"

gText_NewGameAdventureIntro2::
    .string "New paths will open to you when you help\n"
    .string "people in need, overcome challenges,\n"
    .string "and solve mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others to a battle. At other times, you\n"
    .string "will be attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gText_NewGameAdventureIntro3::
    .string "On your travels, we hope that you will\n"
    .string "meet countless people and, through\n"
    .string "them, achieve personal growth.\n"
    .string "That is the most important objective\n"
    .string "of this adventure.\n"
    .string "\n"
    .string "When you're ready, press the A button,\n"
    .string "and let your adventure begin!$"
